version: '2'
services:

  master-1:
    container_name: master-1
    image: hadoop-base-image:latest
    restart: on-failure
    hostname: master-1
    ports:
      - "9870:9870"
      - "8088:8088"
    privileged: true
    stdin_open: true       
    tty: true             
    volumes:
      - "~/src/study/Hadoop/hadoop-cluster/conf:/user/conf"
      - "~/src/study/Hadoop/hadoop-cluster/data:/user/data"
      - "~/src/study/Hadoop/hadoop-cluster/files:/user/files"
    extra_hosts:
      - "master-2:172.20.0.3"
      - "slave-1:172.20.0.4"
      - "slave-2:172.20.0.5"
      - "slave-3:172.20.0.6"

  master-2:
    container_name: master-2
    image: hadoop-base-image:latest
    restart: on-failure
    hostname: master-2
    depends_on:
      - master-1
    privileged: true
    stdin_open: true       
    tty: true   
    extra_hosts:
      - "master-1:172.20.0.2"
      - "slave-1:172.20.0.4"
      - "slave-2:172.20.0.5"
      - "slave-3:172.20.0.6"          

  slave-1:
    container_name: slave-1
    image: hadoop-base-image:latest
    restart: on-failure
    hostname: slave-1
    depends_on:
      - master-1
      - master-2
    privileged: true
    stdin_open: true       
    tty: true        
    extra_hosts:
      - "master-1:172.20.0.2"
      - "master-2:172.20.0.3"
      - "slave-2:172.20.0.5"
      - "slave-3:172.20.0.6"     

  slave-2:
    container_name: slave-2
    image: hadoop-base-image:latest
    restart: on-failure
    hostname: slave-2
    depends_on:
      - master-1
      - master-2
      - slave-1
    privileged: true
    stdin_open: true       
    tty: true       
    extra_hosts:
      - "master-1:172.20.0.2"
      - "master-2:172.20.0.3"
      - "slave-1:172.20.0.4"
      - "slave-3:172.20.0.6"  

  slave-3:
    container_name: slave-3
    image: hadoop-base-image:latest
    restart: on-failure
    hostname: slave-3
    depends_on:
      - master-1
      - master-2
      - slave-1
      - slave-2
    privileged: true
    stdin_open: true       
    tty: true          
    extra_hosts:
      - "master-1:172.20.0.2"
      - "master-2:172.20.0.3"
      - "slave-1:172.20.0.4"
      - "slave-2:172.20.0.5" 